# Generated by Django 5.2.6 on 2025-11-29 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0003_delete_intakes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(help_text='Unique ID for the intake record', primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Date when the medicine is scheduled to be taken')),
                ('scheduled_time', models.TimeField(help_text='Expected time for the medicine intake (e.g., 08:00)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='pending', help_text='Status of the intake (pending/taken/skipped/missed)', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, help_text='Actual datetime when the medicine was taken', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this intake (e.g., side effects, taken with food)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('medicine', models.ForeignKey(help_text='Medicine associated with this intake', on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='medicines.medicines')),
                ('user', models.ForeignKey(help_text='User who owns this intake record', on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intake',
                'verbose_name_plural': 'Intakes',
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'unique_together': {('user', 'medicine', 'scheduled_date', 'scheduled_time')},
            },
        ),
    ]
