# Generated by Django 5.2.6 on 2025-11-29 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique ID for the template",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the template (e.g., 'Blood Pressure', 'Blood Sugar')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'blood-pressure')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this health metric measures",
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for frontend (e.g., 'heart', 'droplet')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category for grouping (e.g., 'cardiovascular', 'metabolic')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="JSON schema defining fields, types, units, and validation rules"
                    ),
                ),
                (
                    "normal_range",
                    models.JSONField(
                        blank=True,
                        help_text="Normal/healthy ranges for each field (for display purposes)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Health Template",
                "verbose_name_plural": "Health Templates",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique ID for the health record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Health metric values following the template schema"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        help_text="When the health measurement was taken"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this measurement",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where the measurement was taken (e.g., 'Home', 'Clinic')",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this health record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template this record is based on",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="health_state.healthtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Record",
                "verbose_name_plural": "Health Records",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
