# Generated by Django 5.2.6 on 2025-10-10 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Metric name like 'Blood Pressure', 'Blood Sugar'",
                        max_length=100,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Flexible JSON for metric configuration"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(
                        help_text="Metric identifier for grouping", max_length=100
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                (
                    "values",
                    models.JSONField(
                        help_text="JSON object containing the metric values"
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(
                        blank=True, help_text="For Blood Pressure", null=True
                    ),
                ),
                (
                    "diastolic",
                    models.IntegerField(
                        blank=True, help_text="For Blood Pressure", null=True
                    ),
                ),
                (
                    "glucose_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For Blood Sugar",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For Weight",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, help_text="For Heart Rate", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="health_metrics.healthmetric",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android (FCM)"),
                            ("ios", "iOS (APNs)"),
                            ("web", "Web Push"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.URLField()),
                (
                    "keys",
                    models.JSONField(
                        default=dict, help_text="Push subscription keys and tokens"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed like 'create', 'update', 'delete'",
                        max_length=50,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Model name that was affected", max_length=50
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(help_text="ID of the affected object"),
                ),
                (
                    "before",
                    models.JSONField(
                        blank=True, help_text="Object state before change", null=True
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True, help_text="Object state after change", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performed_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="health_metr_user_id_6915b7_idx"
                    ),
                    models.Index(
                        fields=["actor"], name="health_metr_actor_i_9e5566_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="health_metr_object__469925_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="health_metr_created_e16384_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="healthmetric",
            index=models.Index(fields=["user"], name="health_metr_user_id_fb82ae_idx"),
        ),
        migrations.AddIndex(
            model_name="healthmetric",
            index=models.Index(
                fields=["user", "name"], name="health_metr_user_id_607cff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="healthmetric",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="metricreading",
            index=models.Index(fields=["user"], name="health_metr_user_id_688261_idx"),
        ),
        migrations.AddIndex(
            model_name="metricreading",
            index=models.Index(
                fields=["user", "metric_key"], name="health_metr_user_id_d1ee42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metricreading",
            index=models.Index(
                fields=["user", "metric_key", "-recorded_at"],
                name="health_metr_user_id_06185b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metricreading",
            index=models.Index(
                fields=["metric"], name="health_metr_metric__d721cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(fields=["user"], name="health_metr_user_id_5912f0_idx"),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="health_metr_user_id_372756_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pushsubscription",
            unique_together={("user", "endpoint")},
        ),
    ]
