# Generated by Django 5.2.6 on 2025-10-10 07:03

import django.core.validators
import django.db.models.deletion
import medicines.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=medicines.models.medicine_image_path,
                    ),
                ),
                ("start_date", models.DateField()),
                ("until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="Asia/Kathmandu", max_length=100),
                ),
                ("time", models.TimeField()),
                ("date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "rrule",
                    models.TextField(
                        blank=True, help_text="RFC5545 RRULE for recurrence", null=True
                    ),
                ),
                (
                    "instruction",
                    models.TextField(
                        blank=True,
                        help_text="Instructions like 'after meal', 'before sleep'",
                        null=True,
                    ),
                ),
                (
                    "dose_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dose_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mg", "Milligrams"),
                            ("g", "Grams"),
                            ("ml", "Milliliters"),
                            ("l", "Liters"),
                            ("units", "Units"),
                            ("drops", "Drops"),
                            ("puffs", "Puffs"),
                            ("pieces", "Pieces"),
                            ("tablets", "Tablets"),
                            ("capsules", "Capsules"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "dose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medicines.medicine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time", "date"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("triggered", "Triggered"),
                            ("snoozed", "Snoozed"),
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                            ("dismissed", "Dismissed"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("next_run", models.DateTimeField(db_index=True)),
                ("snooze_until", models.DateTimeField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="medicines.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run"],
            },
        ),
        migrations.CreateModel(
            name="MedicineAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("injection", "Injection"),
                            ("drops", "Drops"),
                            ("cream", "Cream"),
                            ("ointment", "Ointment"),
                            ("powder", "Powder"),
                            ("inhaler", "Inhaler"),
                            ("patch", "Patch"),
                            ("other", "Other"),
                        ],
                        default="tablet",
                        max_length=50,
                    ),
                ),
                (
                    "composition",
                    models.JSONField(
                        default=dict,
                        help_text="Flexible JSON for medicine composition details",
                    ),
                ),
                (
                    "dose",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dose_unit",
                    models.CharField(
                        choices=[
                            ("mg", "Milligrams"),
                            ("g", "Grams"),
                            ("ml", "Milliliters"),
                            ("l", "Liters"),
                            ("units", "Units"),
                            ("drops", "Drops"),
                            ("puffs", "Puffs"),
                            ("pieces", "Pieces"),
                            ("tablets", "Tablets"),
                            ("capsules", "Capsules"),
                        ],
                        default="mg",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="medicines.medicine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="medicines.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                            ("partial", "Partial"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_dose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "actual_dose_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mg", "Milligrams"),
                            ("g", "Grams"),
                            ("ml", "Milliliters"),
                            ("l", "Liters"),
                            ("units", "Units"),
                            ("drops", "Drops"),
                            ("puffs", "Puffs"),
                            ("pieces", "Pieces"),
                            ("tablets", "Tablets"),
                            ("capsules", "Capsules"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_intakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="medicines.medicine",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="medicines.reminder",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="medicines.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-taken_at", "-scheduled_time"],
            },
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(fields=["user"], name="medicines_m_user_id_03b44f_idx"),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["user", "name"], name="medicines_m_user_id_2c3e8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["user"], name="medicines_s_user_id_b2e181_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["medicine"], name="medicines_s_medicin_e80854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["user", "medicine"], name="medicines_s_user_id_6a446d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["date", "time"], name="medicines_s_date_90ff9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["next_run"],
                name="pending_reminders_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["schedule"], name="medicines_r_schedul_6d14c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(fields=["status"], name="medicines_r_status_246075_idx"),
        ),
        migrations.AddIndex(
            model_name="medicineattribute",
            index=models.Index(
                fields=["medicine"], name="medicines_m_medicin_172ad7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicineattribute",
            index=models.Index(fields=["user"], name="medicines_m_user_id_682403_idx"),
        ),
        migrations.AddIndex(
            model_name="intake",
            index=models.Index(fields=["user"], name="medicines_i_user_id_c26fd7_idx"),
        ),
        migrations.AddIndex(
            model_name="intake",
            index=models.Index(
                fields=["user", "-taken_at"], name="medicines_i_user_id_a77a41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intake",
            index=models.Index(
                fields=["medicine"], name="medicines_i_medicin_10bc3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intake",
            index=models.Index(
                fields=["scheduled_time"], name="medicines_i_schedul_686b05_idx"
            ),
        ),
    ]
