# Generated by Django 5.2.6 on 2025-10-30 14:40

import django.db.models.deletion
import medicines.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicines",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique ID for the medicine",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the medicine", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the medicine", null=True
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="Dose of the medicine (e.g., 500mg, 10ml)",
                        max_length=50,
                    ),
                ),
                (
                    "dose_unit",
                    models.CharField(
                        help_text="Unit of the dose (e.g., 5 , 10)", max_length=50
                    ),
                ),
                (
                    "days_a_week",
                    models.JSONField(
                        help_text="Days of the week the medicine is taken (e.g., [1,2,3] for Mon, Tue, Wed)"
                    ),
                ),
                (
                    "time_of_day",
                    models.JSONField(
                        help_text="Time of day when the medicine is taken (e.g., ['8:00', '12:00']) in 24-hour format"
                    ),
                ),
                (
                    "composition",
                    models.JSONField(
                        blank=True,
                        help_text="Additional composition details (e.g., {'paracetamol': '500mg', 'ingredient2': 'value2'})",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image of the medicine if any or else can be blank",
                        null=True,
                        upload_to=medicines.models.medicine_image_path,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this medicine",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Intakes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique ID for the intake",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("skipped", "Skipped"),
                            ("missed", "Missed"),
                        ],
                        help_text="Status of the intake (e.g., taken, skipped, missed)",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this intake",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        help_text="Medicine who owns this intake",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="medicines.medicines",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake",
                "verbose_name_plural": "Intakes",
                "ordering": ["id"],
            },
        ),
    ]
