# Generated by Django 5.2.6 on 2025-11-26 15:33

import medicines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicines",
            name="composition",
        ),
        migrations.RemoveField(
            model_name="medicines",
            name="days_a_week",
        ),
        migrations.RemoveField(
            model_name="medicines",
            name="description",
        ),
        migrations.RemoveField(
            model_name="medicines",
            name="dose",
        ),
        migrations.RemoveField(
            model_name="medicines",
            name="dose_unit",
        ),
        migrations.RemoveField(
            model_name="medicines",
            name="time_of_day",
        ),
        migrations.AddField(
            model_name="medicines",
            name="amount",
            field=models.IntegerField(
                default=1,
                help_text="Number of units to be taken at a time (e.g., 2 tablets)",
            ),
        ),
        migrations.AddField(
            model_name="medicines",
            name="days_of_week",
            field=models.JSONField(
                default=medicines.models.get_default_days_of_week,
                help_text="Days of the week the medicine is taken (e.g., [1,2,3,4,5,6,7] for Sun-Sat)",
            ),
        ),
        migrations.AddField(
            model_name="medicines",
            name="dosage",
            field=models.IntegerField(
                blank=True,
                help_text="Dosage of the medicine (e.g., 500 for 500mg)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicines",
            name="end_date",
            field=models.DateTimeField(
                blank=True, help_text="End date of the medicine schedule", null=True
            ),
        ),
        migrations.AddField(
            model_name="medicines",
            name="help_message",
            field=models.TextField(
                blank=True,
                help_text="Extra note for the user to remember about this medicine",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicines",
            name="start_date",
            field=models.DateTimeField(
                blank=True, help_text="Start date of the medicine schedule", null=True
            ),
        ),
        migrations.AddField(
            model_name="medicines",
            name="time",
            field=models.JSONField(
                default=medicines.models.get_default_time,
                help_text="Times of day when the medicine is taken (e.g., ['08:00', '14:00', '20:00']) in HH:MM format",
            ),
        ),
    ]
