# Generated by Django 5.2.6 on 2025-11-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_medicines_composition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intakes',
        ),
    ]
